TB-11 file -> SQLite replacing
toto-neutrino1/LearnEnglishWordsTelegramBot pull request #11
Opened 2023-10-01 22:34 UTC by toto-neutrino1

Краткое описание, где что находится.

1) LearnWordsTrainerDatabase - тот же класс LearnWordsTrainer, только работает с базой данных. Создал новый класс, т.к. почти все функции пришлось переделывать под sql-запросы, показалось легче сделать ещё один класс и работать с ним.

2) DatabaseService - почти все функции по прямому взаимодействию с базой данных вынесены сюда. Из названий функций всё понятно, отдельно отмечу функцию **addRightAnswerAndCheckIsLearnedWord** -  добавляет правильный ответ в базу, а также, если данное слово становится "выученным", возвращает true.

3) Изначально думал вообще все публичные функции в LearnWordsTrainerDatabase оставить с теми же именами и параметрами, как в LearnWordsTrainer, но тогда пришлось бы для каждого пользователя создавать свой экземпляр DatabaseService, что было бы неразумно (т.к. DatabaseService вообще никак не привязан ни к какому из пользователей); поэтому экземпляр DatabaseService как параметр во многие функции добавил.

Вопрос насчёт SQL-запросов (особенно длинных) - насколько адекватно они написаны?
Например, в методе getUnlearnedWordsTable() запрос 
`"select * from $WORDS_TABLE where id not in (select word_id from $USER_ANSWERS_TABLE where user_id = $userId and correct_answer_count >= $learningThreshold)"`
- так пишут, или можно и нужно писать по-другому?

2023-10-03 16:16 UTC, danelyan requested changes
Очень круто! Главное сам разобрался ))

По поводу архитектуры все таки вкину замечаний.
1. LearnWordsTrainer я бы оставил в одном экземпляре, только вынес из него работу со словарем. 
Ведь по сути задача трейнера подбирать слова для показа пользователю и проверять их правильность.
Тогда для успешного вынесения логики работы со словарем надо решить 2 задачи
- убрать из LearnWordsTrainer все что связано с работой с файлом
- учесть, что за вынесенной логикой будет БД

Логику работы со словарем можно выразить простым интерфейсом:
```Kotlin
interface IUserDictionary {
    fun getNumOfLearnedWords(): Int
    fun getSize(): Int
    fun getLearnedWords(): List<Word>
    fun getUnlearnedWords(): List<Word>
    fun setCorrectAnswersCount(word: String, correctAnswersCount: Int)
    fun resetUserProgress()
}
```
- Получать размеры в целом можно было бы и получив список и вычесля размер, но база будет делать это эффективнее.
- setCorrectAnswersCount() - нужен чтобы устанавливать количество, чтобы не пересохранять в базу все

Тогда реализация работающая с файлом выглядела бы примерно так:

```Kotlin

class FileUserDictionary(
    private val fileName: String = DEFAULT_FILE_NAME,
    private val learningThreshold: Int = DEFAULT_LEARNING_THRESHOLD,
) : IUserDictionary {

    private val dictionary = try {
        loadDictionary()
    } catch (e: Exception) {
        throw IllegalArgumentException("Некорректный файл")
    }

    // ...

    override fun setCorrectAnswersCount(original: String, correctAnswersCount: Int) {
        dictionary.find { it.original == original }?.correctAnswersCount = correctAnswersCount
        saveDictionary()
    }

    override fun resetUserProgress() {
        dictionary.forEach { it.correctAnswersCount = 0 }
        saveDictionary()
    }

    private fun loadDictionary(): List<Word> {
        val wordsFile = File(fileName)
        // ...
        return dictionary
    }

    private fun saveDictionary() {
        val file = File(fileName)
        val newFileContent = dictionary.map { "${it.original}|${it.translate}|${it.correctAnswersCount}" }
        file.writeText(newFileContent.joinToString(separator = "\n"))
    }

}

```

Ну а реализация работающая с базой вот так:

```Kotlin
class DatabaseUserDictionary(
    val userId: String,
    val databaseService: DatabaseService,
) : IUserDictionary {

    // ...

```

SQL лучше собрать **в одно место**, в твоем случае DatabaseService

# Вопросы 

> I) Вопрос насчёт SQL-запросов (особенно длинных) - насколько адекватно они написаны?
> Например, в методе getUnlearnedWordsTable() возвращается запрос
> "select * from $WORDS_TABLE where id not in (select word_id from $USER_ANSWERS_TABLE where user_id = $userId and correct_answer_count >= $learningThreshold)" - так пишут, или можно и нужно писать по-другому?

Большие запросы это норма. Только давай их форматировать. 
```SQL
select *
from $WORDS_TABLE
where id not in (
        select word_id
        from $USER_ANSWERS_TABLE
        where user_id = $userId
            and correct_answer_count >= $learningThreshold
    )
```

> II) Насчёт обращения к БД - имеет ли смысл закрывать соединение только через некоторое время после отклика от пользователя, или лучше его закрыть, а потом при необходимости открыть заново?
> Например, пользователь получает вопрос => скорее всего он в течение короткого времени (скажем, 10 с) кликнет на какую-нибудь кнопку; лучше подождать условные 10 с и не закрывать соединение, или лучше его закрыть и снова открыть только при его клике на кнопку?

В целом соединение можно не закрывать. Обычно в приложении делают один экземпляр сервиса для доступа к базе данных и используют его в разных модулях приложения. А закрывают соединение при выходе из приложения.

> III) При сбросе прогресса я удаляю все записи пользователя из таблицы user_answers_table; но можно записи не удалять, а обнулить в них значения correct_answers_count - какой вариант предпочтительнее?
> Или удаление/вставка +- одно и то же в БД по времени, и это непринципиально?

Лучше обнулить, так как в будущем ты возможно захочешь прикрутить авторизацию, или хранить время регистрации пользователя (чтобы построить график привлечения пользователей) и забудешь, что один из методов дропает всю таблицу.
Удаление/вставка +/- одно и то же. 
Но на самом деле в продуктовых базах принято ничего не удалять, а помечать в специальной колонке deleted в true. На случай если пользователь придет в поддержку, и пожалуется на случайное удаление всего. А потом, когда место заканчивается делают удаление всех записей у которых deleted=true

2023-10-03 17:23 UTC, danelyan requested changes

2023-10-03 17:23 UTC, danelyan commented on src/main/kotlin/DatabaseService.kt
> +                            "insert into $USERS_TABLE values(${lastId + 1}, '$username', '$date', $chatId)"
Вот тут самое время рассказать про SQL-инъекции.
Представь что username будет `','',200000);--"`.
Кавычка вначале закроет sql поле, то есть, итоговый запрос будет таким:
```SQL
insert into $USERS_TABLE values(${lastId + 1}, '','',200000); -- , '$date', $chatId)
```
Таким образом мы установим произвольный chat_id в базе.
Да пример не очень полезный )) первое что пришло в голову.

Вот тут еще примерчики что можно делать с инъекциями:
https://www.invicti.com/blog/web-security/sql-injection-cheat-sheet/

А починить можно при помощи prepareStatement():
```
    val statement =
        connection.prepareStatement(
            "INSERT INTO $USERS_TABLE (id, username, created_at, chat_id) values (?, ?, ?, ?)");
    statement.setInt(1, lastId + 1)
    statement.setString(2, username)
    statement.setString(3, date)
    statement.setLong(4, chatId)
    statement.executeUpdate()
```

2023-10-27 20:52 UTC, toto-neutrino1 commented on src/main/kotlin/DatabaseService.kt
> +                            "insert into $USERS_TABLE values(${lastId + 1}, '$username', '$date', $chatId)"
Спасибо за подробные комментарии! )

Вроде всё поправил. 
Инъекции вставил только в нескольких местах, где на вход sql подаются строки.

2023-10-28 13:05 UTC, danelyan requested changes
Вижу только пару замечаний )

2023-10-28 13:05 UTC, danelyan commented on src/main/kotlin/DatabaseService.kt
> +        val statement = connection.createStatement()
Давай везде использовать prepareStatement

2023-10-28 13:05 UTC, danelyan commented on src/main/kotlin/DatabaseService.kt
> +        var learnedWords = listOf<Word>()
Эта переменная не нужна

2023-10-28 13:05 UTC, danelyan commented on src/main/kotlin/DatabaseService.kt
> +                injectionStatement.setInt(1, lastId + 1)
Можно так:
```Kotlin
  connection.prepareStatement(
      """
          insert into $USERS_TABLE 
          values(?, ?, ?, ?)
      """.trimIndent()
  ).apply {
      setInt(1, lastId + 1)
      setString(2, username)
      setString(3, date)
      setLong(4, chatId)
      executeUpdate()
  }
```

2023-10-28 13:05 UTC, danelyan commented on src/main/kotlin/DatabaseService.kt
> +            injectionStatement.setInt(1, indexOfLine + FIRST_WORDS_INDEX + lastId)
тут аналогично можно применить apply{}

2023-10-29 19:02 UTC, danelyan approved these changes
Теперь отлично!

2023-10-30 14:29 UTC, merged