TB-4 add startLearningWords() method (first variant)
toto-neutrino1/LearnEnglishWordsTelegramBot pull request #4
Opened 2023-08-22 22:53 UTC by toto-neutrino1

2023-08-24 19:35 UTC, danelyan requested changes

2023-08-24 19:35 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val unlearnedWords = dictionary.filter { it.correctAnswersCount < learningThreshold }.toMutableList()
toMutableList() - лишняя операция, в целом желательно стремиться к иммутабельности, если это возможно

2023-08-24 19:35 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            println("\nВаши дальнейшие действия: \n1 - продолжить изучение слов, 2 - вернуться в главное меню")
Не очень удобно, после каждого ответа на вопрос вводить 1, чтобы продолжить изучение слов. Давай добавим пункт меню 0, в дополнение к вариантам ответа. При вводе 0 - выходим в основное меню

2023-08-24 19:35 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            while (answer !in listOf("1", "2", "3", "4")) {
не очень универсально получается, мы "хардкодим" поведение ориентированное на 4 варианта ответа. Давай просто проверять, что если у нас не число, не 0 и не равно индексу правильного ответа - что ответ неправильный. Так мы сильно упростим логику и сократим код

2023-08-24 19:35 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            val shuffledWords = unlearnedWords.shuffled().take(4)
4 лучше вынести в константу с понятным именем

2023-08-24 20:10 UTC, toto-neutrino1 commented on src/main/kotlin/Main.kt
> +        val unlearnedWords = dictionary.filter { it.correctAnswersCount < learningThreshold }.toMutableList()
Изначально хотел первой строкой в функции startLearningWords() создать MutableList, чтобы по ходу изучения слов исключать выученные слова (чтобы не приходилось каждый раз заново фильтровать исходный dictionary) - насколько это в принципе имеет смысл?

Предполагаю, что поскольку сложность фильтрования O(n), а словарь не супер большой, это вряд ли сильно повлияет на скорость работы; интересно как это на самом деле

2023-08-24 20:35 UTC, toto-neutrino1 commented on src/main/kotlin/Main.kt
> +        val unlearnedWords = dictionary.filter { it.correctAnswersCount < learningThreshold }.toMutableList()
Спасибо за ценные замечания!
Вроде всё исправил

2023-08-26 07:36 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val unlearnedWords = dictionary.filter { it.correctAnswersCount < learningThreshold }.toMutableList()
Круто, что задумываешься о сложности. И ты прав, на таком небольшом словаре это не сильно скажется на производительности. На самом деле сама архитектура изначально не подразумевает больших словарей, ведь мы по сути вычитываем и парсим весь словарь из файла в память. 

Для больших словарей правильнее было бы использовать базу данных (хотя бы sqlite). В БД как правило поиск осуществляется по индексу, а чтение по курсору - то есть не все данные грузятся в память.

Другой вариант, сделать отдельный класс Dictionary. Который под капотом не выгружал в память весь словарь, а только лишь его часть. В реальности, еще бы добавить мониторинг, который подсчитывал скорость выгрузки файла и прочее интересующее нас.

2023-08-26 07:37 UTC, danelyan approved these changes
Да, теперь хорошо.
Ответил в комменте выше на твой вопрос, а мы двигаемся дальше )

2023-08-26 11:02 UTC, toto-neutrino1 commented on src/main/kotlin/Main.kt
> +        val unlearnedWords = dictionary.filter { it.correctAnswersCount < learningThreshold }.toMutableList()
Понял, буду разбираться, спасибо!

2023-08-26 11:03 UTC, merged