TB-6 add LearnWordsTrainer class
toto-neutrino1/LearnEnglishWordsTelegramBot pull request #6
Opened 2023-08-27 22:46 UTC by toto-neutrino1

2023-08-30 12:15 UTC, danelyan requested changes
> Практически весь свой предыдущий код оставил как есть, разбив его на функции (в первую очередь это касается метода startLearningWords()).

Разбивка 

Из того, что чуть изменил и отличается от материалов из видео, стоит отметить переменную rightWord - в ней будет храниться слово, которое гарантированно не изучено (актуально, когда неизученных слов осталось меньше 4); сделал так, чтобы для перевода не выдавалось слово, которое уже изучено (для 4 слов может это не так критично, но если например слов будет 10, в конце изучения слишком часто будут попадаться знакомые слова).

Дополнительные дата-классы решил не вводить, мне показалось, что без них всё нормально структурировано

2023-08-30 12:15 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        println("Выучено $numOfLearnedWords из $numOfAllWords слов | $learnedPercent%")
Метод printStatistics() выполняет две задачи:
1. Вычисляет статистику
2. Печатает статистику в консоль

И вот этот второй пункт делает метод `printStatistics()` не универсальным. Ты не сможешь использовать его, к примеру, в Android приложении или в следующих этапах, где мы используем класс LearnWordsTrainer в телеграм боте.

И это как раз таки одна из причин введения data-класса Statistics - это **часть интерфейса LearnWordsTrainer для получения статистики**.

Поэтому давай тут создавать Statistics, возвращать его, а в коде консольного тренажера печатать результат в консоль

2023-08-30 12:15 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        while (true) {
Тут аналогичная проблема - этот цикл часть консольного тренажера. 
Да, код стал более опрятным, все разложено по полочкам и по нему стало удобнее навигироваться.
Но универсальность LearnWordsTrainer тут же и заканчивается. У тренажера должны быть методы для получения вариантов ответа и метод проверки правильности ответа. А то как отрисовываются варианты ответа уже определяют другие классы. Для Android это могла бы быть Activity, для телеграм-бота будет отдельный сервис

2023-08-30 18:19 UTC, toto-neutrino1 commented on src/main/kotlin/LearnWordsTrainer.kt
> +        println("Выучено $numOfLearnedWords из $numOfAllWords слов | $learnedPercent%")
А, всё, понял зачем было столько разделений на классы/методы, что отправить в консольную часть, а что - нет.
Спасибо! )

2023-08-30 20:34 UTC, toto-neutrino1 commented on src/main/kotlin/LearnWordsTrainer.kt
> +        while (true) {
Вроде всё поправил, разделил консольную и тренажерную часть.

В нескольких местах использовал scope-функцию with(), чтобы избавиться от необходимости обращаться к конкретному объекту напрямую.
В частности, в функции checkAnswer() без использования with() проверка выглядела бы так:
`if (userAnswer.toIntOrNull() == question.questionWords.indexOf(question.rightAnswer) + 1)`

2023-09-05 06:33 UTC, danelyan requested changes
Да, стало намного лучше!
Давай последний момент поправим и пойдем дальше

2023-09-05 06:33 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        with(question) {
последний выданный question мы можем хранить в самом LearnWordsTrainer, тогда не нужно его передавать для проверки внутрь

2023-09-05 10:55 UTC, toto-neutrino1 commented on src/main/kotlin/LearnWordsTrainer.kt
> +        with(question) {
Добавил. 
То, что свойство lateinit, никак не мешает - т.к. проверка ответа у меня проводится только если question не равен null, даже если все слова при первом запуске программы выучены, никаких проблем не возникнет

2023-09-05 11:03 UTC, danelyan approved these changes
Хорошо. Идем дальше!

2023-09-05 11:03 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        with(question) {
ок, давай пока оставим. Но в целом - лучше уж оставлять nullable, впрочем - дальше еще будет этап, где придется ее сделать публичной )

2023-09-05 12:04 UTC, merged